-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Left:  ViewSonic VA270-FHD (HDMI-A-1) -- 1920x1080 @ 100 Hz
hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080@100.08",
	position = "0x0",
	scale = 1,
})

-- Center: Gigabyte M28U (DP-1) -- 4K @ 144 Hz, 2x scale (same as KDE)
hl.monitor({
	output = "DP-1",
	mode = "3840x2160@144.00",
	position = "1920x0",
	scale = 2,
})

-- Right: AOC 27G2ZNE (DP-2) -- 1920x1080 @ 240 Hz
hl.monitor({
	output = "DP-2",
	mode = "1920x1080@240.00",
	position = "3840x0",
	scale = 1,
})

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "kitty"
local fileManager = "dolphin"
-- SUPER on its own = the rofi app launcher, toggled: SUPER again closes it.
-- `menu` is the toggle wrapper, not the rofi command line itself. The wrapper
-- owns the rofi flags because Hyprland's exec dispatcher does not reliably
-- pass a multi-word argument through to it -- see the comment at the top of
-- rofi-toggle.sh, which also explains why the toggle lives in a script rather
-- than being a second bare `menu` exec.
local menu = "/home/maxii/.config/hypr/scripts/rofi-toggle.sh"
-- The scratchpad notepad. One variable for all three uses below -- autostart, the
-- toggle bind, and the click-away binds -- so a move or a reinstall cannot leave
-- one of them pointing at a path that no longer exists. An absolute path rather
-- than a bare `hypr-scratch` on purpose: binds run with a minimal environment and
-- PATH is not guaranteed to include ~/.local/bin.
local HYPR_SCRATCH = "/home/maxii/.local/bin/hypr-scratch"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notification daemons, status bars, etc.)

hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpaper") -- wallpaper daemon
	hl.exec_cmd("quickshell -c tokyonight") -- status bar (quickshell tokyonight bar; waybar config backed up in gh:Zsweezzy/waybar-dotfiles)
	hl.exec_cmd("openrgb --startminimized") -- RGB control; start to tray, no UI on launch
	-- Apollo: Moonlight GameStream server. Start the unit, not the binary, because
	-- its ExecStartPre settle delay and Restart= are part of the behaviour, and the
	-- xdg-autostart target it is enabled against never activates under Hyprland.
	hl.exec_cmd("systemctl --user start apollo")
	-- Warm the shortcuts/apps launcher so Super+K only has to reveal it.
	hl.exec_cmd("/home/maxii/.local/bin/hypr-shortcut-launcher --background")
	-- Warm the scratchpad notepad so Super+N only has to reveal it.
	hl.exec_cmd(HYPR_SCRATCH .. " --background")
	-- Clipboard history daemon (cliphist): watch text + image selections and store them
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	-- Neru: keyboard-driven hints (Ctrl+Shift+Space). Absolute path because
	-- autostart runs with a minimal environment and ~/.local/bin is not
	-- guaranteed to be on PATH, the same reason HYPR_SCRATCH is absolute.
	hl.exec_cmd("/home/maxii/.local/bin/neru launch")
	hl.exec_cmd("/usr/bin/opendeck --hide") -- OpenDeck stream controllers; start to tray, no UI on launch
	-- ponytail: workaround, Hyprland 0.56.2 executes this config file twice at
	-- startup, so every hl.bind lands in the bind list twice and one SUPER+Q
	-- ran kitty twice (the keybind manager fires every matching bind). A reload
	-- rebuilds the list from a fresh lua state in a single pass and does not
	-- re-fire hyprland.start, so autostart stays single. Delete this once
	-- upstream stops loading the config twice. sleep 2 so the reload lands
	-- after startup monitor setup.
	hl.exec_cmd("sleep 2 && hyprctl reload")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

-- Cursor matching KDE (kcminputrc): Bibata-Modern-Classic @ 22px
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "22")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "22")

-- Terminal the Super+K launcher opens a command in. Same variable as the
-- SUPER+Q bind, so changing `terminal` above moves both at once.
hl.env("HYPR_LAUNCHER_TERMINAL", terminal)

-- Render XWayland apps (ONLYOFFICE, Wine, etc.) at native 1x instead of
-- texture-scaling them on the scaled 4K monitor. Text stays sharp; these apps
-- appear smaller on DP-1 (scale 2) but full-size on the 1080p monitors.
hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- Qt/KDE apps (Kate, Dolphin, Konsole…) read kdeglobals (TokyoNightMoon)
-- instead of rendering light; also via ~/.config/environment.d/qt.conf
hl.env("QT_QPA_PLATFORMTHEME", "kde")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in = 3, -- was 5: 2px smaller space between windows
		gaps_out = 6, -- was 20: same as gaps_in, windows sit close to monitor edges

		border_size = 2,

		col = {
			-- Tokyo Night Moon palette, same 45° colorflow gradient:
			--   blue   #82aaff  (moon blue)   -> replaces #33ccff
			--   orange #ff9e64  (moon orange) -> replaces #9ece6a green
			active_border = { colors = { "rgba(82aaffee)", "rgba(ff9e64ee)" }, angle = 45 },
			inactive_border = "rgba(2f334daa)", -- moon bg_highlight #2f334d
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "dwindle",
	},

	decoration = {
		rounding = 10,
		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.0,

		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee16161e, -- tokyo night moon bg_dark #16161e
		},

		blur = {
			enabled = true,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
			-- Blur regardless of a surface's own alpha. This is already the
			-- default; stated explicitly because hypr-scratch is deliberately
			-- translucent and depends on blur for its frosted look.
			ignore_opacity = true,
		},
	},

	animations = {
		enabled = true,
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
-- Keep layer-shell fades snappy, including the launcher's overlay transitions
-- (0.8 deciseconds is about 80ms).
hl.animation({ leaf = "layers", enabled = true, speed = 0.8, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 0.8, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 0.8, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 0.8, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 0.8, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
-- Super+S is the magic scratchpad (SUPER toggles special:magic, SUPER+SHIFT+S
-- sends a window into it). `specialWorkspace*` is unset in the tree above, so it
-- inherits `workspaces` -- which is `fade` here, and a scratchpad that just
-- materialises in place reads as a glitch rather than as an arrival.
--
-- `slidevert bottom` is the forced-side form: the second token picks the sign
-- rather than the axis, so "bottom" means +Y coming in (fly up from the bottom
-- edge) and the outgoing leg needs "top" to send the workspace back down and
-- out of the same edge it arrived through. Token order is load-bearing --
-- WorkspaceAnimationController reads args[1] for the side and the *last* token for
-- the travel percentage -- so any percentage would have to go after the side, and
-- the wiki's "slidevert 20% bottom" order silently drops it and slides sideways.
--
-- There is no switch for the fade. Hyprland hardcodes alpha 0->1 on the way in
-- and 1->0 on the way out for every special workspace whatever the style is
-- (WorkspaceAnimationController.cpp), and alpha shares the one animation config
-- with the render offset, so style cannot decouple them. easeOutQuint is the
-- lever: its output is ~0.9 by a third of the way through, so opacity is
-- effectively full while the window is still travelling and the dissolve is not
-- there to see. A spring is deliberately avoided -- its overshoot bounces the
-- alpha as well as the offset.
--
-- Scale on top of the travel is not available here, and it is not a config miss.
-- One leaf carries one style, and the special-workspace controller only animates
-- two things for the whole workspace: alpha and a render offset (translation).
-- There is no scale channel, and the per-window styles that do scale -- popin 85%,
-- gnomed -- live on the window's own map/unmap controller, which a special
-- workspace toggle never runs. So it is travel or scale, not both: this is the
-- travel. For the scale instead, the scratchpad would have to stop being a
-- special workspace and open as a normal window under `animation = popin 85%`.
hl.animation({ leaf = "specialWorkspaceIn", enabled = true, speed = 4.79, bezier = "easeOutQuint", style = "slidevert bottom" })
hl.animation({ leaf = "specialWorkspaceOut", enabled = true, speed = 1.49, bezier = "linear", style = "slidevert top" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "de",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		-- 1: focus follows the pointer. There is still no cursor-moving bind in
		-- this config (`hyprctl binds` has zero `movecursor` dispatchers), so
		-- SUPER+arrow moves focus from the focused window rather than from
		-- wherever the pointer happens to be. Steam games opt out per-window via
		-- `no_follow_mouse` in `steam-game-fullscreen`; read that rule with this.
		follow_mouse = 1,

		-- Pointer settings mirroring KDE (kcminputrc):
		--   PointerAcceleration=-0.400  -> libinput pointer speed -0.4
		--   PointerAccelerationProfile=1 -> flat (no acceleration)
		-- Bumped one tick faster, then half a tick slower: -0.4 -> -0.2 -> -0.3
		sensitivity = -0.3, -- -1.0 - 1.0, 0 means no modification.
		accel_profile = "flat",

		touchpad = {
			natural_scroll = false,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Lua-backed Hyprland bindings are reported by hyprctl as __lua with an
-- internal numeric action id. Provide descriptions so the launcher can show
-- what each shortcut does instead of that implementation detail.
local function describedBind(key, dispatcher, description, options)
	options = options or {}
	options.description = description
	return hl.bind(key, dispatcher, options)
end

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
describedBind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal), "Open terminal")
-- SUPER + K = searchable Hyprland shortcuts and running-app switcher
describedBind(mainMod .. " + K", hl.dsp.exec_cmd("/home/maxii/.local/bin/hypr-shortcut-launcher"), "Open shortcuts and apps launcher")
-- SUPER + N = floating iced scratchpad notepad (toggle)
describedBind(mainMod .. " + N", hl.dsp.exec_cmd(HYPR_SCRATCH), "Toggle scratchpad notepad")
-- SUPER + C = force-close the focused app (SIGKILL, no "you sure?" prompt).
-- hl.dsp.window.kill() kills the process instead of sending a graceful close
-- request, so apps can't show save/close confirmations.
describedBind(mainMod .. " + C", hl.dsp.window.kill(), "Kill focused window")

-- SUPER + SHIFT + C = graceful close: ASK the focused app to shut down, so an app
-- that supports the request can prompt to save. An app that ignores it is killed
-- by the compositor regardless — silently, since this bind says nothing.
describedBind(mainMod .. " + SHIFT + C", hl.dsp.window.close(), "Close focused window")

describedBind(mainMod .. " + M", hl.dsp.exit(), "Log out or exit Hyprland")
describedBind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager), "Open file manager")
describedBind(mainMod .. " + W", hl.dsp.exec_cmd("firefox"), "Open Firefox")
-- SUPER + D = launch a second copy of the app in the focused window, on the
-- current workspace, via that window's own command line rather than its class
-- name. Steam moved to SUPER + T only because this chord was taken; whether a
-- Steam window survives the script is incidental to the guard it runs, which
-- refuses whatever the host cannot resolve and knows nothing about Steam.
describedBind(mainMod .. " + T", hl.dsp.exec_cmd("steam"), "Open Steam")
describedBind(mainMod .. " + D", hl.dsp.exec_cmd("/home/maxii/.config/hypr/scripts/duplicate-window.sh"), "Duplicate focused window")
describedBind(mainMod .. " + SHIFT + V", hl.dsp.window.float({ action = "toggle" }), "Toggle focused window floating")
-- SUPER on its own = the rofi app launcher, toggled: SUPER again closes it.
-- `menu` (above) is the toggle wrapper, not the rofi command line: the wrapper
-- owns the rofi flags, because a multi-word argument appended to a bind here
-- does not survive dispatch intact.
--
-- This is the "modkey only" bind, which is a special case: a bare `bind = SUPER,
-- ...` registers fine (hyprctl shows it, with an empty key) but never reaches
-- the dispatcher. The documented way to bind a modkey by itself is the release
-- form with the target key named explicitly -- see "Binding modkeys only" in
-- the wiki (https://wiki.hypr.land/Configuring/Binds/), whose example is
-- `bindr = SUPER ALT, Alt_L, exec, amongus`. Naming the key and adding the
-- release flag is what makes it a modkey bind rather than a chord that is
-- missing its second key.
--
-- allow_input_capture is what makes the closing half of the toggle work: rofi
-- grabs the keyboard while it is open, and a normal bind is not dispatched
-- while a client holds that grab, so SUPER again would be swallowed by rofi
-- instead of reaching this bind.
--
-- Known risk: upstream issue hyprwm/Hyprland#6946 tracks this regressing, with
-- a report of it still failing on 0.56.2 (the version this session runs). If
-- bare SUPER stays dead, put the launcher back on a chord -- SUPER + R worked.
describedBind(
	mainMod .. " + SUPER_L",
	hl.dsp.exec_cmd(menu),
	"Open application launcher",
	{ release = true, allow_input_capture = true }
)
-- Clipboard history (cliphist): SUPER + V opens history in rofi,
-- picking an entry copies it back to the clipboard (paste with Ctrl+V / SUPER+V)
describedBind(
	mainMod .. " + V",
	hl.dsp.exec_cmd("cliphist list | rofi -dmenu -i -monitor DP-1 | cliphist decode | wl-copy"),
	"Open clipboard history"
)
describedBind(mainMod .. " + P", hl.dsp.window.pseudo(), "Toggle pseudo-terminal")
describedBind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized" }), "Maximize focused window") -- fills monitor, keeps gaps + borders
describedBind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen(), "Toggle fullscreen") -- fills monitor, no gaps/borders
describedBind(mainMod .. " + J", hl.dsp.layout("togglesplit"), "Toggle split layout") -- dwindle only

-- Move focus with mainMod + arrow keys
describedBind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }), "Focus window left")
describedBind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), "Focus window right")
describedBind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }), "Focus window up")
describedBind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }), "Focus window down")

-- Rearrange windows with the keyboard:
--   SUPER + SHIFT + arrows = move focused window in a direction
--     (works even when fullscreen: script unfullscreens, moves, refullscreens)
--   SUPER + ALT + arrows   = swap focused window with its neighbor
describedBind(mainMod .. " + SHIFT + left", hl.dsp.exec_cmd("/home/maxii/.config/hypr/scripts/move-fullscreen.sh left"), "Move focused window left")
describedBind(mainMod .. " + SHIFT + right", hl.dsp.exec_cmd("/home/maxii/.config/hypr/scripts/move-fullscreen.sh right"), "Move focused window right")
describedBind(mainMod .. " + SHIFT + up", hl.dsp.exec_cmd("/home/maxii/.config/hypr/scripts/move-fullscreen.sh up"), "Move focused window up")
describedBind(mainMod .. " + SHIFT + down", hl.dsp.exec_cmd("/home/maxii/.config/hypr/scripts/move-fullscreen.sh down"), "Move focused window down")
describedBind(mainMod .. " + ALT + left", hl.dsp.window.swap({ direction = "left" }), "Swap focused window left")
describedBind(mainMod .. " + ALT + right", hl.dsp.window.swap({ direction = "right" }), "Swap focused window right")
describedBind(mainMod .. " + ALT + up", hl.dsp.window.swap({ direction = "up" }), "Swap focused window up")
describedBind(mainMod .. " + ALT + down", hl.dsp.window.swap({ direction = "down" }), "Swap focused window down")

-- Screenshots with grim + slurp
--   Print       = current active monitor only
--   SHIFT+Print = region select, confined to the active monitor (edges act as snap boundaries)
describedBind("print", hl.dsp.exec_cmd("mkdir -p /home/maxii/Pictures/Screenshots && f=/home/maxii/Pictures/Screenshots/$(date +%F_%H-%M-%S).png && grim -o \"$(hyprctl activeworkspace -j | jq -r .monitor)\" - | tee \"$f\" | wl-copy && notify-send -a screenshot 'Screenshot saved (active monitor)' \"$(basename \"$f\")\""), "Take screenshot of active monitor")
describedBind("SHIFT + print", hl.dsp.exec_cmd("mkdir -p /home/maxii/Pictures/Screenshots && f=/home/maxii/Pictures/Screenshots/$(date +%F_%H-%M-%S).png && grim -g \"$(slurp -o \"$(hyprctl activeworkspace -j | jq -r .monitor)\")\" - | tee \"$f\" | wl-copy && notify-send -a screenshot 'Screenshot saved (region)' \"$(basename \"$f\")\""), "Take screenshot of selected region")

-- SUPER + Print = open the most recent screenshot with qView
describedBind(mainMod .. " + print", hl.dsp.exec_cmd("latest=$(ls -t /home/maxii/Pictures/Screenshots/*.png 2>/dev/null | head -1); [ -n \"$latest\" ] && flatpak run com.interversehq.qView \"$latest\" || notify-send -u critical -a screenshot 'No screenshots yet'"), "Open latest screenshot")

-- Switch workspaces with mainMod + [0-9]
-- Send active window to a workspace without following it with mainMod + SHIFT + [0-9]
-- Move active window to a workspace and follow it with mainMod + CTRL + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	describedBind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }), "Focus workspace " .. i)
	describedBind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i, follow = false }), "Send focused window to workspace " .. i)
	describedBind(mainMod .. " + CTRL + " .. key, hl.dsp.window.move({ workspace = i }), "Move focused window to workspace " .. i .. " (follow)")
end

-- Example special workspace (scratchpad)
describedBind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"), "Toggle magic workspace")
describedBind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }), "Move focused window to magic workspace")

-- The NZXT Lift Elite's two thumb buttons. Codes read off the raw evdev stream
-- on /dev/input/event2 rather than guessed: 276 (BTN_EXTRA) is the front button,
-- 275 (BTN_SIDE) the back one. Hyprland has no per-device binds, so these are
-- global -- but no other attached mouse emits 275/276 (the GMMK trackball module
-- declares them and never sends them).
--
-- The workspace chords reuse the dispatchers from the SUPER + [0-9] loop above:
-- SUPER = switch, SUPER + SHIFT = send the window without following. Chords and
-- bare buttons coexist; Hyprland matches binds on (modmask, key).
describedBind("CTRL + mouse:276", hl.dsp.workspace.toggle_special("magic"), "Toggle magic workspace (mouse)")
-- The "out" move has no keyboard equivalent: hl.window.move has no `previous`
-- selector, but `monitor = "current"` resolves to the focused monitor's
-- m_activeWorkspace, which stays the normal workspace sitting behind the
-- scratchpad. Moving out of a special workspace also closes it.
describedBind("CTRL + mouse:275", hl.dsp.window.move({ monitor = "current" }), "Send magic-workspace window back to the workspace behind it (mouse)")
describedBind(mainMod .. " + mouse:275", hl.dsp.focus({ workspace = 1 }), "Focus workspace 1 (mouse)")
describedBind(mainMod .. " + mouse:276", hl.dsp.focus({ workspace = 4 }), "Focus workspace 4 (mouse)")
describedBind(mainMod .. " + SHIFT + mouse:275", hl.dsp.window.move({ workspace = 1, follow = false }), "Send focused window to workspace 1 (mouse)")
describedBind(mainMod .. " + SHIFT + mouse:276", hl.dsp.window.move({ workspace = 4, follow = false }), "Send focused window to workspace 4 (mouse)")

-- Scroll through existing workspaces with mainMod + scroll
describedBind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), "Focus next existing workspace")
describedBind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }), "Focus previous existing workspace")

-- Move/resize windows with mainMod + LMB/RMB and dragging
describedBind(mainMod .. " + mouse:272", hl.dsp.window.drag(), "Drag focused window", { mouse = true })
describedBind(mainMod .. " + mouse:273", hl.dsp.window.resize(), "Resize focused window", { mouse = true })

-- Click outside rofi to close it (rofi's own -click-to-exit is broken on Wayland:
-- rofi only creates its own layer surface, so outside clicks never reach it)
describedBind(
	"mouse:272",
	hl.dsp.exec_cmd("/home/maxii/.config/hypr/scripts/rofi-outside-click.sh"),
	"Close rofi on outside click (LMB)",
	{ non_consuming = true }
)
describedBind(
	"mouse:273",
	hl.dsp.exec_cmd("/home/maxii/.config/hypr/scripts/rofi-outside-click.sh"),
	"Close rofi on outside click (RMB)",
	{ non_consuming = true }
)

-- Click outside the scratchpad notepad to save and hide it. Same reason as the
-- rofi binds above, and for the same reason it has to be asked of the
-- compositor rather than done in the app: GTK4 removed the client-side pointer
-- grab API, so a window that is not grabbing never hears about clicks outside
-- itself, and the notepad cannot grab without losing focus-away dismissal.
--
-- Unlike the rofi script this must not kill anything -- the notepad has unsaved
-- text and is expected to still be there for the next hotkey -- so it tells the
-- running instance to save and hide, over the notepad's own socket.
-- `non_consuming` for the same reason as rofi: the click has to reach the window
-- underneath, so that focusing something else and dismissing the notepad are one
-- gesture rather than two.
--
-- `--outside-click` is a mode of the notepad's own binary rather than a script,
-- so there is nothing to keep in sync and nothing to install but the binary. It
-- does not touch the socket unless the click landed outside, and does nothing at
-- all if the notepad is not running, so it is safe to leave bound to bare clicks.
--
-- A third and fourth bind on these two buttons, which Hyprland allows; the
-- mouse:272/273 drag and resize binds above are on a modifier and do not
-- collide.
describedBind(
	"mouse:272",
	hl.dsp.exec_cmd(HYPR_SCRATCH .. " --outside-click"),
	"Dismiss scratchpad notepad on outside click (LMB)",
	{ non_consuming = true }
)
describedBind(
	"mouse:273",
	hl.dsp.exec_cmd(HYPR_SCRATCH .. " --outside-click"),
	"Dismiss scratchpad notepad on outside click (RMB)",
	{ non_consuming = true }
)

-- Laptop multimedia keys for volume and LCD brightness
describedBind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	"Raise volume",
	{ locked = true, repeating = true }
)
describedBind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	"Lower volume",
	{ locked = true, repeating = true }
)
describedBind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	"Mute audio",
	{ locked = true, repeating = true }
)
describedBind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	"Mute microphone",
	{ locked = true, repeating = true }
)
describedBind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), "Increase screen brightness", { locked = true, repeating = true })
describedBind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), "Decrease screen brightness", { locked = true, repeating = true })

-- Requires playerctl
describedBind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), "Play next media track", { locked = true })
describedBind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), "Play or pause media", { locked = true })
describedBind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), "Play or pause media", { locked = true })
describedBind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), "Play previous media track", { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Iced glass and overlay behaviour for the scratchpad notepad. The panel is
-- only 0.72 opaque in GTK, so blur plus the global vibrancy setting is what
-- produces the frost. `no_blur = false` means "do blur this window"; size,
-- passes and vibrancy come from the global decoration.blur block and are
-- shared with every other window, so this rule can only ask for blur on or
-- off, not tune it.
--
-- The notepad is a normal toplevel, not a layer surface. That is deliberate: a
-- layer surface that holds the keyboard traps the session -- Hyprland will not
-- move focus off it, so clicking away does nothing and the notepad can only be
-- dismissed by its own hotkey. As a real window it gets honest focus
-- semantics, so it closes when you click away or focus something else.
--
-- That means the overlay look is the compositor's job. GTK4 removed the client
-- side window hints (keep-above, skip-taskbar, type), so without this rule the
-- notepad would open tiled and snapped into the layout. `pin` keeps it above
-- everything; `float` keeps it out of the layout; `center` puts it in the
-- middle of the monitor it opens on, which the app then corrects to the main
-- display. `no_focus` is deliberately NOT set: the notepad has to take the
-- keyboard when it opens.
--
-- The class is the GTK application ID, verbatim: GTK4 puts it on the toplevel
-- as the Wayland app id and Hyprland reports that as the class. It is not
-- `hypr-scratch` as it was when the notepad was a layer surface with an
-- explicit namespace.
--
-- The `.*` on both sides is not decoration. Hyprland matches a window rule
-- against the *whole* class rather than a substring of it, so a bare
-- "HyprScratch" matches nothing at all and the notepad quietly opens tiled and
-- unfocused.
--
-- Every key below is checked against Hyprland's own list of window-rule effect
-- keys (src/desktop/rule/windowRule/WindowRuleEffectContainer.cpp). Two keys
-- that used to be here are not on it, and both were silently doing nothing:
--
--   no_border  There is no such effect. The list has `border_size`, which is
--              the real spelling; see below.
--   suppress_event as a table  This one takes a *space-separated string*,
--              not a list. A table is the kind of thing `luac -p` happily
--              accepts and Hyprland then ignores, which is why it survived.
--
-- `rounding = 10` is `decoration.rounding` restated. The notepad's corners are
-- actually painted by the app's own CSS, not by this -- with `rounding = 0`
-- here the compositor leaves the surface square and the arc is still there --
-- but setting both to the same number means the two layers cannot disagree
-- about how round the window is, whichever one ends up painting.
hl.window_rule({
	name = "hypr-scratch-overlay",
	match = { class = ".*HyprScratch.*" },
	float = true,
	center = true,
	pin = true,
	border_size = 0,
	no_shadow = true,
	no_anim = true,
	no_blur = false,
	rounding = 10,
	suppress_event = "maximize fullscreen",
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})

-- Open every new application window on the main center monitor.
hl.window_rule({
	name = "open-on-main-monitor",
	match = { class = ".*" },
	monitor = "DP-1",
})

-- Steam games are fullscreen on the main panel, workspace 10. Must come AFTER
-- the catch-all above: windowrules match top-to-bottom and the first match
-- wins, so the `class = ".*"` rule would otherwise consume these windows and
-- this one would never fire.
--
-- The monitor is keyed by NAME, not id. Monitor ids are enum-order and shift
-- across reboots (id 1 currently resolves to DP-2, a different panel), so a
-- numeric `monitor = 1` lands games on the wrong screen unpredictably.
--
-- `no_follow_mouse` opts the game out of `input.follow_mouse`. A fullscreen
-- game captures the pointer, so any mouse move Hyprland reads over the game
-- surface would hand focus away from it and the in-game cursor sticks where it
-- was captured. The opt-out only does anything while `follow_mouse` is non-zero,
-- so the two settings are coupled and must be read together.
hl.window_rule({
	name = "steam-game-fullscreen",
	match = { class = "^steam_app_\\d+$" },
	fullscreen = true,
	monitor = "DP-1",
	workspace = 10,
	no_follow_mouse = true,
})

-- Workspace 10 is the Steam-games workspace, and everything on it is
-- fullscreen, so a border and rounded corners draw over nothing but the game's
-- own pixels — visual noise, and a visible seam at the screen edges.
--
-- These keys are `no_border` / `no_rounding` on 0.56.2. `border = false` /
-- `rounding = false` is the 0.47-era spelling of the same thing and is now
-- silently dropped as an unknown field — third time this file got bitten by it
-- (window-rule `no_border`, `suppress_event` as a table, this). Neither the lua
-- binding nor the json printer complains; `configerrors` is the only report.
--
-- That spelling is workspace-rule-specific: on `hl.window_rule` `no_border` is
-- an unknown field and `border_size` is the equivalent — see the
-- `hypr-scratch-overlay` comment above.
hl.workspace_rule({
	workspace = "10",
	no_border = true,
	no_rounding = true,
})

-- Steam notification toasts (friend online, achievements) must survive a
-- fullscreen game on another workspace. Without this they silently vanish, and
-- the cause is compositor-side, not Steam: the toasts are XWayland windows of
-- class `steam` titled `notificationtoasts_<n>_desktop`, and Hyprland culls
-- every window that is not "allowed over fullscreen"
-- (Renderer.cpp, shouldRenderWindow). The policy that grants it
-- (WindowFullscreenPolicy.cpp, effectiveAllowedOverFullscreen) allows only four
-- cases: the fullscreen window itself, a *pinned* window, one explicitly
-- permitted, or one grouped with the fullscreen window. A toast is none of
-- those, so it gets dropped.
--
-- `pin` satisfies the policy in one move and also fixes the second half of the
-- bug: pinned windows render on every workspace, so a toast raised while
-- Steam itself sits on another workspace still appears over the game. That is
-- the whole reason these were invisible with the game on ws4 and Steam on 1-3.
--
-- `float` is not optional. Pinning is ignored for tiled windows, so without it
-- the pin silently does nothing.
--
-- `no_focus` because a notification must never steal focus from a running game;
-- the toast still draws and still takes clicks.
--
-- Tradeoff: a pinned window renders on every connected monitor, so the toast
-- appears in the corner of all three displays. That is the cost of not missing
-- it, and it is why this is scoped by title to the toasts alone rather than
-- pinning all of Steam.
hl.window_rule({
	name = "steam-toast-over-fullscreen",
	match = {
		class = "^steam$",
		title = "^notificationtoasts_.*_desktop$",
	},
	float = true,
	pin = true,
	no_focus = true,
})
